spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-4h8gzuof.us.auth0.com/
          audiences: https://jwtresourceapi
logging:
  level:
    org:
      springframework:
        security: debug
